name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
